//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="ServiceReference1.TextCasingSoapType")]
    public interface TextCasingSoapType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TitleCaseWordsWithTokenResponse> TitleCaseWordsWithTokenAsync(ServiceReference1.TitleCaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.InvertStringCaseResponse> InvertStringCaseAsync(ServiceReference1.InvertStringCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.InvertCaseFirstAdjustStringToPreviousResponse> InvertCaseFirstAdjustStringToPreviousAsync(ServiceReference1.InvertCaseFirstAdjustStringToPreviousRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.InvertCaseFirstAdjustStringToCurrentResponse> InvertCaseFirstAdjustStringToCurrentAsync(ServiceReference1.InvertCaseFirstAdjustStringToCurrentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AllUppercaseWithTokenResponse> AllUppercaseWithTokenAsync(ServiceReference1.AllUppercaseWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AllLowercaseWithTokenResponse> AllLowercaseWithTokenAsync(ServiceReference1.AllLowercaseWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.UppercaseWordsWithTokenResponse> UppercaseWordsWithTokenAsync(ServiceReference1.UppercaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.LowercaseWordsWithTokenResponse> LowercaseWordsWithTokenAsync(ServiceReference1.LowercaseWordsWithTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleCaseWordsWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleCaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.TitleCaseWordsWithTokenRequestBody Body;
        
        public TitleCaseWordsWithTokenRequest()
        {
        }
        
        public TitleCaseWordsWithTokenRequest(ServiceReference1.TitleCaseWordsWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class TitleCaseWordsWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public TitleCaseWordsWithTokenRequestBody()
        {
        }
        
        public TitleCaseWordsWithTokenRequestBody(string sText, string sToken)
        {
            this.sText = sText;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleCaseWordsWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleCaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.TitleCaseWordsWithTokenResponseBody Body;
        
        public TitleCaseWordsWithTokenResponse()
        {
        }
        
        public TitleCaseWordsWithTokenResponse(ServiceReference1.TitleCaseWordsWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class TitleCaseWordsWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TitleCaseWordsWithTokenResult;
        
        public TitleCaseWordsWithTokenResponseBody()
        {
        }
        
        public TitleCaseWordsWithTokenResponseBody(string TitleCaseWordsWithTokenResult)
        {
            this.TitleCaseWordsWithTokenResult = TitleCaseWordsWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertStringCaseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertStringCase", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.InvertStringCaseRequestBody Body;
        
        public InvertStringCaseRequest()
        {
        }
        
        public InvertStringCaseRequest(ServiceReference1.InvertStringCaseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertStringCaseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertStringCaseRequestBody()
        {
        }
        
        public InvertStringCaseRequestBody(string sAString)
        {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertStringCaseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertStringCaseResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.InvertStringCaseResponseBody Body;
        
        public InvertStringCaseResponse()
        {
        }
        
        public InvertStringCaseResponse(ServiceReference1.InvertStringCaseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertStringCaseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertStringCaseResult;
        
        public InvertStringCaseResponseBody()
        {
        }
        
        public InvertStringCaseResponseBody(string InvertStringCaseResult)
        {
            this.InvertStringCaseResult = InvertStringCaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToPreviousRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToPrevious", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.InvertCaseFirstAdjustStringToPreviousRequestBody Body;
        
        public InvertCaseFirstAdjustStringToPreviousRequest()
        {
        }
        
        public InvertCaseFirstAdjustStringToPreviousRequest(ServiceReference1.InvertCaseFirstAdjustStringToPreviousRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToPreviousRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertCaseFirstAdjustStringToPreviousRequestBody()
        {
        }
        
        public InvertCaseFirstAdjustStringToPreviousRequestBody(string sAString)
        {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToPreviousResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToPreviousResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.InvertCaseFirstAdjustStringToPreviousResponseBody Body;
        
        public InvertCaseFirstAdjustStringToPreviousResponse()
        {
        }
        
        public InvertCaseFirstAdjustStringToPreviousResponse(ServiceReference1.InvertCaseFirstAdjustStringToPreviousResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToPreviousResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertCaseFirstAdjustStringToPreviousResult;
        
        public InvertCaseFirstAdjustStringToPreviousResponseBody()
        {
        }
        
        public InvertCaseFirstAdjustStringToPreviousResponseBody(string InvertCaseFirstAdjustStringToPreviousResult)
        {
            this.InvertCaseFirstAdjustStringToPreviousResult = InvertCaseFirstAdjustStringToPreviousResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToCurrentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToCurrent", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.InvertCaseFirstAdjustStringToCurrentRequestBody Body;
        
        public InvertCaseFirstAdjustStringToCurrentRequest()
        {
        }
        
        public InvertCaseFirstAdjustStringToCurrentRequest(ServiceReference1.InvertCaseFirstAdjustStringToCurrentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToCurrentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertCaseFirstAdjustStringToCurrentRequestBody()
        {
        }
        
        public InvertCaseFirstAdjustStringToCurrentRequestBody(string sAString)
        {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToCurrentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToCurrentResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.InvertCaseFirstAdjustStringToCurrentResponseBody Body;
        
        public InvertCaseFirstAdjustStringToCurrentResponse()
        {
        }
        
        public InvertCaseFirstAdjustStringToCurrentResponse(ServiceReference1.InvertCaseFirstAdjustStringToCurrentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToCurrentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertCaseFirstAdjustStringToCurrentResult;
        
        public InvertCaseFirstAdjustStringToCurrentResponseBody()
        {
        }
        
        public InvertCaseFirstAdjustStringToCurrentResponseBody(string InvertCaseFirstAdjustStringToCurrentResult)
        {
            this.InvertCaseFirstAdjustStringToCurrentResult = InvertCaseFirstAdjustStringToCurrentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUppercaseWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUppercaseWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.AllUppercaseWithTokenRequestBody Body;
        
        public AllUppercaseWithTokenRequest()
        {
        }
        
        public AllUppercaseWithTokenRequest(ServiceReference1.AllUppercaseWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllUppercaseWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public AllUppercaseWithTokenRequestBody()
        {
        }
        
        public AllUppercaseWithTokenRequestBody(string sAString, string sToken)
        {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUppercaseWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUppercaseWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.AllUppercaseWithTokenResponseBody Body;
        
        public AllUppercaseWithTokenResponse()
        {
        }
        
        public AllUppercaseWithTokenResponse(ServiceReference1.AllUppercaseWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllUppercaseWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AllUppercaseWithTokenResult;
        
        public AllUppercaseWithTokenResponseBody()
        {
        }
        
        public AllUppercaseWithTokenResponseBody(string AllUppercaseWithTokenResult)
        {
            this.AllUppercaseWithTokenResult = AllUppercaseWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllLowercaseWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllLowercaseWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.AllLowercaseWithTokenRequestBody Body;
        
        public AllLowercaseWithTokenRequest()
        {
        }
        
        public AllLowercaseWithTokenRequest(ServiceReference1.AllLowercaseWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllLowercaseWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public AllLowercaseWithTokenRequestBody()
        {
        }
        
        public AllLowercaseWithTokenRequestBody(string sAString, string sToken)
        {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllLowercaseWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllLowercaseWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.AllLowercaseWithTokenResponseBody Body;
        
        public AllLowercaseWithTokenResponse()
        {
        }
        
        public AllLowercaseWithTokenResponse(ServiceReference1.AllLowercaseWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllLowercaseWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AllLowercaseWithTokenResult;
        
        public AllLowercaseWithTokenResponseBody()
        {
        }
        
        public AllLowercaseWithTokenResponseBody(string AllLowercaseWithTokenResult)
        {
            this.AllLowercaseWithTokenResult = AllLowercaseWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UppercaseWordsWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UppercaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.UppercaseWordsWithTokenRequestBody Body;
        
        public UppercaseWordsWithTokenRequest()
        {
        }
        
        public UppercaseWordsWithTokenRequest(ServiceReference1.UppercaseWordsWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class UppercaseWordsWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public UppercaseWordsWithTokenRequestBody()
        {
        }
        
        public UppercaseWordsWithTokenRequestBody(string sAString, string sToken)
        {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UppercaseWordsWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UppercaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.UppercaseWordsWithTokenResponseBody Body;
        
        public UppercaseWordsWithTokenResponse()
        {
        }
        
        public UppercaseWordsWithTokenResponse(ServiceReference1.UppercaseWordsWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class UppercaseWordsWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UppercaseWordsWithTokenResult;
        
        public UppercaseWordsWithTokenResponseBody()
        {
        }
        
        public UppercaseWordsWithTokenResponseBody(string UppercaseWordsWithTokenResult)
        {
            this.UppercaseWordsWithTokenResult = UppercaseWordsWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LowercaseWordsWithTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LowercaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.LowercaseWordsWithTokenRequestBody Body;
        
        public LowercaseWordsWithTokenRequest()
        {
        }
        
        public LowercaseWordsWithTokenRequest(ServiceReference1.LowercaseWordsWithTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class LowercaseWordsWithTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public LowercaseWordsWithTokenRequestBody()
        {
        }
        
        public LowercaseWordsWithTokenRequestBody(string sAString, string sToken)
        {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LowercaseWordsWithTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LowercaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ServiceReference1.LowercaseWordsWithTokenResponseBody Body;
        
        public LowercaseWordsWithTokenResponse()
        {
        }
        
        public LowercaseWordsWithTokenResponse(ServiceReference1.LowercaseWordsWithTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class LowercaseWordsWithTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LowercaseWordsWithTokenResult;
        
        public LowercaseWordsWithTokenResponseBody()
        {
        }
        
        public LowercaseWordsWithTokenResponseBody(string LowercaseWordsWithTokenResult)
        {
            this.LowercaseWordsWithTokenResult = LowercaseWordsWithTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface TextCasingSoapTypeChannel : ServiceReference1.TextCasingSoapType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TextCasingSoapTypeClient : System.ServiceModel.ClientBase<ServiceReference1.TextCasingSoapType>, ServiceReference1.TextCasingSoapType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TextCasingSoapTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(TextCasingSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), TextCasingSoapTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TextCasingSoapTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TextCasingSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TextCasingSoapTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TextCasingSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TextCasingSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.TitleCaseWordsWithTokenResponse> ServiceReference1.TextCasingSoapType.TitleCaseWordsWithTokenAsync(ServiceReference1.TitleCaseWordsWithTokenRequest request)
        {
            return base.Channel.TitleCaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TitleCaseWordsWithTokenResponse> TitleCaseWordsWithTokenAsync(string sText, string sToken)
        {
            ServiceReference1.TitleCaseWordsWithTokenRequest inValue = new ServiceReference1.TitleCaseWordsWithTokenRequest();
            inValue.Body = new ServiceReference1.TitleCaseWordsWithTokenRequestBody();
            inValue.Body.sText = sText;
            inValue.Body.sToken = sToken;
            return ((ServiceReference1.TextCasingSoapType)(this)).TitleCaseWordsWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.InvertStringCaseResponse> ServiceReference1.TextCasingSoapType.InvertStringCaseAsync(ServiceReference1.InvertStringCaseRequest request)
        {
            return base.Channel.InvertStringCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InvertStringCaseResponse> InvertStringCaseAsync(string sAString)
        {
            ServiceReference1.InvertStringCaseRequest inValue = new ServiceReference1.InvertStringCaseRequest();
            inValue.Body = new ServiceReference1.InvertStringCaseRequestBody();
            inValue.Body.sAString = sAString;
            return ((ServiceReference1.TextCasingSoapType)(this)).InvertStringCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.InvertCaseFirstAdjustStringToPreviousResponse> ServiceReference1.TextCasingSoapType.InvertCaseFirstAdjustStringToPreviousAsync(ServiceReference1.InvertCaseFirstAdjustStringToPreviousRequest request)
        {
            return base.Channel.InvertCaseFirstAdjustStringToPreviousAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InvertCaseFirstAdjustStringToPreviousResponse> InvertCaseFirstAdjustStringToPreviousAsync(string sAString)
        {
            ServiceReference1.InvertCaseFirstAdjustStringToPreviousRequest inValue = new ServiceReference1.InvertCaseFirstAdjustStringToPreviousRequest();
            inValue.Body = new ServiceReference1.InvertCaseFirstAdjustStringToPreviousRequestBody();
            inValue.Body.sAString = sAString;
            return ((ServiceReference1.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToPreviousAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.InvertCaseFirstAdjustStringToCurrentResponse> ServiceReference1.TextCasingSoapType.InvertCaseFirstAdjustStringToCurrentAsync(ServiceReference1.InvertCaseFirstAdjustStringToCurrentRequest request)
        {
            return base.Channel.InvertCaseFirstAdjustStringToCurrentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InvertCaseFirstAdjustStringToCurrentResponse> InvertCaseFirstAdjustStringToCurrentAsync(string sAString)
        {
            ServiceReference1.InvertCaseFirstAdjustStringToCurrentRequest inValue = new ServiceReference1.InvertCaseFirstAdjustStringToCurrentRequest();
            inValue.Body = new ServiceReference1.InvertCaseFirstAdjustStringToCurrentRequestBody();
            inValue.Body.sAString = sAString;
            return ((ServiceReference1.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToCurrentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AllUppercaseWithTokenResponse> ServiceReference1.TextCasingSoapType.AllUppercaseWithTokenAsync(ServiceReference1.AllUppercaseWithTokenRequest request)
        {
            return base.Channel.AllUppercaseWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AllUppercaseWithTokenResponse> AllUppercaseWithTokenAsync(string sAString, string sToken)
        {
            ServiceReference1.AllUppercaseWithTokenRequest inValue = new ServiceReference1.AllUppercaseWithTokenRequest();
            inValue.Body = new ServiceReference1.AllUppercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ServiceReference1.TextCasingSoapType)(this)).AllUppercaseWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AllLowercaseWithTokenResponse> ServiceReference1.TextCasingSoapType.AllLowercaseWithTokenAsync(ServiceReference1.AllLowercaseWithTokenRequest request)
        {
            return base.Channel.AllLowercaseWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AllLowercaseWithTokenResponse> AllLowercaseWithTokenAsync(string sAString, string sToken)
        {
            ServiceReference1.AllLowercaseWithTokenRequest inValue = new ServiceReference1.AllLowercaseWithTokenRequest();
            inValue.Body = new ServiceReference1.AllLowercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ServiceReference1.TextCasingSoapType)(this)).AllLowercaseWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.UppercaseWordsWithTokenResponse> ServiceReference1.TextCasingSoapType.UppercaseWordsWithTokenAsync(ServiceReference1.UppercaseWordsWithTokenRequest request)
        {
            return base.Channel.UppercaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UppercaseWordsWithTokenResponse> UppercaseWordsWithTokenAsync(string sAString, string sToken)
        {
            ServiceReference1.UppercaseWordsWithTokenRequest inValue = new ServiceReference1.UppercaseWordsWithTokenRequest();
            inValue.Body = new ServiceReference1.UppercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ServiceReference1.TextCasingSoapType)(this)).UppercaseWordsWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.LowercaseWordsWithTokenResponse> ServiceReference1.TextCasingSoapType.LowercaseWordsWithTokenAsync(ServiceReference1.LowercaseWordsWithTokenRequest request)
        {
            return base.Channel.LowercaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LowercaseWordsWithTokenResponse> LowercaseWordsWithTokenAsync(string sAString, string sToken)
        {
            ServiceReference1.LowercaseWordsWithTokenRequest inValue = new ServiceReference1.LowercaseWordsWithTokenRequest();
            inValue.Body = new ServiceReference1.LowercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ServiceReference1.TextCasingSoapType)(this)).LowercaseWordsWithTokenAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TextCasingSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TextCasingSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TextCasingSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.dataaccess.com/webservicesserver/TextCasing.wso");
            }
            if ((endpointConfiguration == EndpointConfiguration.TextCasingSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.dataaccess.com/webservicesserver/TextCasing.wso");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TextCasingSoap,
            
            TextCasingSoap12,
        }
    }
}
